"""
Django settings for mirador project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Lo que cambia entre desarrollo y producción se lee de variables de
# entorno, con valores por defecto que mantienen el `runserver` local
# funcionando sin configurar nada (mismo patrón que peluqueria_mascota).

# SECURITY WARNING: keep the secret key used in production secret!
# En producción SIEMPRE viene de DJANGO_SECRET_KEY (Render la genera sola).
# Sin esa variable (desarrollo local), se genera una al vuelo en cada arranque.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or get_random_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]

CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'anymail',
    'clinica',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mirador.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mirador.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# Sin DATABASE_URL (desarrollo), se usa SQLite. En producción, Render
# provee DATABASE_URL automáticamente al conectar un servicio de Postgres
# propio de este cliente (no compartido con peluqueria_mascota).

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/
# WhiteNoise sirve los estáticos del admin directamente desde la app en
# producción (el frontend React vive aparte, servido por su propio build).

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Django REST Framework + JWT
# El frontend (React/Vite) es un cliente separado: toda la autenticación
# pasa por token JWT, no por sesión/cookie de Django.

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}


# CORS
# Sin DJANGO_CORS_ALLOWED_ORIGINS (desarrollo), se permite el dev server
# por defecto de Vite. En producción hay que apuntarlo al dominio real
# del frontend (ej. https://clinicadentalelmirador.devquad.cl).

CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.environ.get(
        'DJANGO_CORS_ALLOWED_ORIGINS',
        'http://localhost:5173' if DEBUG else '',
    ).split(',') if o.strip()
]


# Email (confirmación de reserva y recordatorio de cita).
# Se manda por la API HTTP de Resend (vía django-anymail), no por SMTP:
# Render bloquea el tráfico saliente a los puertos SMTP (25/465/587) en
# servicios del plan free -- la conexión se queda colgada contra el
# firewall hasta hacer timeout, lo que tira abajo el worker de gunicorn a
# mitad de la petición (ver SIGKILL en logs). La API HTTP usa el puerto
# 443, que no está bloqueado.
# Sin EMAIL_HOST_PASSWORD (desarrollo, o producción mientras no se
# configure un proveedor real), se usa el backend de consola: los correos
# se imprimen en los logs en vez de enviarse, así el flujo se puede
# probar entero sin credenciales reales y sin que una reserva falle por esto.

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173' if DEBUG else '')

if os.environ.get('EMAIL_HOST_PASSWORD'):
    EMAIL_BACKEND = 'anymail.backends.resend.EmailBackend'
    ANYMAIL = {'RESEND_API_KEY': os.environ['EMAIL_HOST_PASSWORD']}
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get(
    # Provisorio: hasta que la clínica configure su propio correo de envío
    # (o se elija un proveedor real, ej. Resend/SendGrid), se usa el de
    # DevQuad para no mandar nada desde la cuenta real de la clínica todavía.
    'DEFAULT_FROM_EMAIL', 'Clínica Dental El Mirador <contacto@devquad.cl>'
)

# A dónde llega el aviso de "nueva reserva" para el staff. Provisorio (etapa
# de pruebas): un correo de DevQuad, NO el correo real de la clínica, para
# que ninguna reserva de prueba le llegue a la clínica todavía. Cambiar a la
# casilla real de la clínica cuando el sistema entre en producción de verdad.
CLINICA_EMAIL_NOTIFICACIONES = os.environ.get('CLINICA_EMAIL_NOTIFICACIONES', 'contacto@devquad.cl')


# Seguridad en producción (Render termina TLS en su proxy y reenvía por HTTP interno).

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7  # 7 días; se puede subir una vez confirmado que todo sirve por HTTPS
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True


# Logging: manda todo a stdout/stderr, que es lo que Render captura como los
# logs del servicio.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
